<?php
/**
 * Database schema definitions.
 *
 * @package Super_Mechanic
 */

namespace Super_Mechanic\Database;

defined( 'ABSPATH' ) || exit;

/**
 * Defines the plugin database schema.
 */
class Schema {
	/**
	 * Get the current schema version.
	 *
	 * @return string
	 */
	public static function get_schema_version() {
		return '1.22.0';
	}

	/**
	 * Get all plugin tables using the active WordPress prefix.
	 *
	 * @return array<string, string>
	 */
	public static function get_tables() {
		global $wpdb;

		return array(
			'businesses'        => $wpdb->prefix . 'sm_businesses',
			'clients'           => $wpdb->prefix . 'sm_clients',
			'client_crm_meta'   => $wpdb->prefix . 'sm_client_crm_meta',
			'crm_pipeline'      => $wpdb->prefix . 'sm_crm_pipeline',
			'crm_tasks'         => $wpdb->prefix . 'sm_crm_tasks',
			'crm_alerts'        => $wpdb->prefix . 'sm_crm_alerts',
			'vehicles'          => $wpdb->prefix . 'sm_vehicles',
			'vehicle_catalog'   => $wpdb->prefix . 'sm_vehicle_catalog',
			'client_vehicles'   => $wpdb->prefix . 'sm_client_vehicles',
			'flows'             => $wpdb->prefix . 'sm_flows',
			'flow_steps'        => $wpdb->prefix . 'sm_flow_steps',
			'processes'         => $wpdb->prefix . 'sm_processes',
			'appointments'      => $wpdb->prefix . 'sm_appointments',
			'appointment_calendar_sync' => $wpdb->prefix . 'sm_appointment_calendar_sync',
			'process_step_logs' => $wpdb->prefix . 'sm_process_step_logs',
			'process_parts'     => $wpdb->prefix . 'sm_process_parts',
			'process_meta'      => $wpdb->prefix . 'sm_process_meta',
			'maintenance'       => $wpdb->prefix . 'sm_maintenance',
			'maintenance_parts' => $wpdb->prefix . 'sm_maintenance_parts',
			'maintenance_labor' => $wpdb->prefix . 'sm_maintenance_labor',
			'pre_delivery'      => $wpdb->prefix . 'sm_pre_delivery',
			'paperwork'         => $wpdb->prefix . 'sm_paperwork',
			'paperwork_items'   => $wpdb->prefix . 'sm_paperwork_items',
			'quotes'            => $wpdb->prefix . 'sm_quotes',
			'quote_items'       => $wpdb->prefix . 'sm_quote_items',
			'invoices'          => $wpdb->prefix . 'sm_invoices',
			'invoice_items'     => $wpdb->prefix . 'sm_invoice_items',
			'payments'          => $wpdb->prefix . 'sm_payments',
			'attachments'       => $wpdb->prefix . 'sm_attachments',
			'comments'          => $wpdb->prefix . 'sm_comments',
			'notifications'     => $wpdb->prefix . 'sm_notifications',
			'webhooks'          => $wpdb->prefix . 'sm_webhooks',
			'webhook_deliveries' => $wpdb->prefix . 'sm_webhook_deliveries',
			'saas_queue_jobs'   => $wpdb->prefix . 'sm_saas_queue_jobs',
		);
	}

	/**
	 * Get dbDelta-compatible SQL statements for all plugin tables.
	 *
	 * @return array<string>
	 */
	public static function get_sql() {
		global $wpdb;

		$tables                = self::get_tables();
		$charset_collate       = $wpdb->get_charset_collate();
		$businesses_table      = $tables['businesses'];
		$clients_table         = $tables['clients'];
		$client_crm_meta_table = $tables['client_crm_meta'];
		$crm_pipeline_table   = $tables['crm_pipeline'];
		$crm_tasks_table      = $tables['crm_tasks'];
		$crm_alerts_table     = $tables['crm_alerts'];
		$vehicles_table        = $tables['vehicles'];
		$vehicle_catalog_table = $tables['vehicle_catalog'];
		$client_vehicles_table = $tables['client_vehicles'];
		$flows_table           = $tables['flows'];
		$flow_steps_table      = $tables['flow_steps'];
		$processes_table       = $tables['processes'];
		$appointments_table    = $tables['appointments'];
		$appointment_sync_table = $tables['appointment_calendar_sync'];
		$step_logs_table       = $tables['process_step_logs'];
		$parts_table           = $tables['process_parts'];
		$process_meta_table    = $tables['process_meta'];
		$maintenance_table     = $tables['maintenance'];
		$maintenance_parts     = $tables['maintenance_parts'];
		$maintenance_labor     = $tables['maintenance_labor'];
		$pre_delivery_table    = $tables['pre_delivery'];
		$paperwork_table       = $tables['paperwork'];
		$paperwork_items_table = $tables['paperwork_items'];
		$quotes_table          = $tables['quotes'];
		$quote_items_table     = $tables['quote_items'];
		$invoices_table        = $tables['invoices'];
		$invoice_items_table   = $tables['invoice_items'];
		$payments_table        = $tables['payments'];
		$attachments_table     = $tables['attachments'];
		$comments_table        = $tables['comments'];
		$notifications_table   = $tables['notifications'];
		$webhooks_table        = $tables['webhooks'];
		$webhook_deliveries_table = $tables['webhook_deliveries'];
		$saas_queue_jobs_table = $tables['saas_queue_jobs'];

		return array(
			"CREATE TABLE {$businesses_table} (
				id bigint(20) unsigned NOT NULL auto_increment,
				slug varchar(80) NOT NULL,
				name varchar(191) NOT NULL,
				status varchar(20) NOT NULL default 'active',
				is_default tinyint(1) NOT NULL default 0,
				timezone varchar(64) NOT NULL default 'UTC',
				currency varchar(10) NOT NULL default 'USD',
				branding_logo_attachment_id bigint(20) unsigned DEFAULT NULL,
				primary_color varchar(20) DEFAULT NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY slug (slug),
				KEY status (status),
				KEY is_default (is_default)
			) {$charset_collate};",
			"CREATE TABLE {$clients_table} (
				id bigint(20) unsigned NOT NULL auto_increment,
				business_id bigint(20) unsigned NOT NULL default 1,
				first_name varchar(100) NOT NULL,
				last_name varchar(100) DEFAULT NULL,
				email varchar(190) DEFAULT NULL,
				phone varchar(50) DEFAULT NULL,
				document_id varchar(100) DEFAULT NULL,
				notes text DEFAULT NULL,
				status varchar(50) NOT NULL default 'active',
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY business_id (business_id),
				KEY email (email),
				KEY phone (phone),
				KEY status (status)
			) {$charset_collate};",
			"CREATE TABLE {$client_crm_meta_table} (
				id bigint(20) unsigned NOT NULL auto_increment,
				business_id bigint(20) unsigned NOT NULL default 1,
				client_id bigint(20) unsigned NOT NULL,
				crm_status varchar(30) NOT NULL default 'lead',
				assigned_user_id bigint(20) unsigned DEFAULT NULL,
				last_contact_at datetime DEFAULT NULL,
				next_follow_up_at datetime DEFAULT NULL,
				commercial_notes longtext DEFAULT NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY business_client (business_id,client_id),
				KEY business_id (business_id),
				KEY client_id (client_id),
				KEY crm_status (crm_status),
				KEY assigned_user_id (assigned_user_id),
				KEY next_follow_up_at (next_follow_up_at)
			) {$charset_collate};",
			"CREATE TABLE {$crm_pipeline_table} (
				id bigint(20) unsigned NOT NULL auto_increment,
				business_id bigint(20) unsigned NOT NULL default 1,
				client_id bigint(20) unsigned NOT NULL,
				vehicle_id bigint(20) unsigned DEFAULT NULL,
				process_id bigint(20) unsigned DEFAULT NULL,
				stage varchar(30) NOT NULL default 'new_lead',
				title varchar(190) NOT NULL,
				estimated_value decimal(12,2) NOT NULL default 0.00,
				currency varchar(10) NOT NULL default 'USD',
				assigned_user_id bigint(20) unsigned DEFAULT NULL,
				notes longtext DEFAULT NULL,
				position int(10) unsigned NOT NULL default 0,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY business_id (business_id),
				KEY client_id (client_id),
				KEY vehicle_id (vehicle_id),
				KEY process_id (process_id),
				KEY stage (stage),
				KEY assigned_user_id (assigned_user_id),
				KEY business_stage_position (business_id,stage,position)
			) {$charset_collate};",
			"CREATE TABLE {$crm_tasks_table} (
				id bigint(20) unsigned NOT NULL auto_increment,
				business_id bigint(20) unsigned NOT NULL default 1,
				crm_pipeline_id bigint(20) unsigned NOT NULL,
				title varchar(190) NOT NULL,
				task_type varchar(30) NOT NULL default 'follow_up',
				assigned_user_id bigint(20) unsigned DEFAULT NULL,
				due_at datetime DEFAULT NULL,
				status varchar(20) NOT NULL default 'pending',
				notes longtext DEFAULT NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY business_id (business_id),
				KEY crm_pipeline_id (crm_pipeline_id),
				KEY task_type (task_type),
				KEY assigned_user_id (assigned_user_id),
				KEY due_at (due_at),
				KEY status (status),
				KEY business_status_due (business_id,status,due_at)
			) {$charset_collate};",
			"CREATE TABLE {$crm_alerts_table} (
				id bigint(20) unsigned NOT NULL auto_increment,
				business_id bigint(20) unsigned NOT NULL default 1,
				crm_pipeline_id bigint(20) unsigned NOT NULL,
				alert_type varchar(40) NOT NULL,
				status varchar(20) NOT NULL default 'active',
				message varchar(255) NOT NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY business_id (business_id),
				KEY crm_pipeline_id (crm_pipeline_id),
				KEY alert_type (alert_type),
				KEY status (status),
				KEY business_pipeline_type_status (business_id,crm_pipeline_id,alert_type,status)
			) {$charset_collate};",
			"CREATE TABLE {$vehicles_table} (
				id bigint(20) unsigned NOT NULL auto_increment,
				business_id bigint(20) unsigned NOT NULL default 1,
				client_id bigint(20) unsigned NOT NULL,
				type varchar(50) NOT NULL,
				make varchar(100) NOT NULL,
				model varchar(100) NOT NULL,
				year smallint(5) unsigned DEFAULT NULL,
				catalog_vehicle_id bigint(20) unsigned DEFAULT NULL,
				trim_version varchar(150) DEFAULT NULL,
				body_type varchar(80) DEFAULT NULL,
				fuel_type varchar(80) DEFAULT NULL,
				transmission varchar(80) DEFAULT NULL,
				engine varchar(150) DEFAULT NULL,
				vin varchar(100) DEFAULT NULL,
				plate varchar(50) DEFAULT NULL,
				color varchar(50) DEFAULT NULL,
				mileage bigint(20) unsigned DEFAULT NULL,
				notes text DEFAULT NULL,
				status varchar(50) NOT NULL default 'active',
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY business_id (business_id),
				KEY client_id (client_id),
				KEY catalog_vehicle_id (catalog_vehicle_id),
				KEY vin (vin),
				KEY plate (plate),
				KEY status (status)
			) {$charset_collate};",
			"CREATE TABLE {$vehicle_catalog_table} (
				id bigint(20) unsigned NOT NULL auto_increment,
				business_id bigint(20) unsigned NOT NULL default 1,
				make varchar(100) NOT NULL,
				model varchar(100) NOT NULL,
				year smallint(5) unsigned DEFAULT NULL,
				trim_version varchar(150) DEFAULT NULL,
				body_type varchar(80) DEFAULT NULL,
				fuel_type varchar(80) DEFAULT NULL,
				transmission varchar(80) DEFAULT NULL,
				engine varchar(150) DEFAULT NULL,
				notes text DEFAULT NULL,
				status varchar(50) NOT NULL default 'active',
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY business_id (business_id),
				KEY make_model (make,model),
				KEY year (year),
				KEY status (status),
				KEY business_status (business_id,status)
			) {$charset_collate};",
			"CREATE TABLE {$client_vehicles_table} (
				id bigint(20) unsigned NOT NULL auto_increment,
				business_id bigint(20) unsigned NOT NULL default 1,
				client_id bigint(20) unsigned NOT NULL,
				vehicle_id bigint(20) unsigned NOT NULL,
				ownership_type varchar(50) NOT NULL default 'owner',
				start_date date NOT NULL,
				end_date date DEFAULT NULL,
				is_primary tinyint(1) NOT NULL default 0,
				created_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY business_id (business_id),
				KEY client_id (client_id),
				KEY vehicle_id (vehicle_id),
				KEY ownership_type (ownership_type),
				KEY is_primary (is_primary),
				KEY current_owner (vehicle_id,end_date,is_primary)
			) {$charset_collate};",
			"CREATE TABLE {$flows_table} (
				id bigint(20) unsigned NOT NULL auto_increment,
				name varchar(150) NOT NULL,
				slug varchar(150) NOT NULL,
				flow_type varchar(50) NOT NULL,
				process_type varchar(50) DEFAULT NULL,
				description text DEFAULT NULL,
				is_default tinyint(1) NOT NULL default 0,
				is_active tinyint(1) NOT NULL default 1,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY slug (slug),
				KEY flow_type (flow_type),
				KEY process_type (process_type),
				KEY is_active (is_active)
			) {$charset_collate};",
			"CREATE TABLE {$flow_steps_table} (
				id bigint(20) unsigned NOT NULL auto_increment,
				flow_id bigint(20) unsigned NOT NULL,
				step_key varchar(100) NOT NULL,
				step_label varchar(150) NOT NULL,
				step_order int(10) unsigned NOT NULL default 0,
				step_type varchar(50) NOT NULL default 'standard',
				is_required tinyint(1) NOT NULL default 0,
				is_initial tinyint(1) NOT NULL default 0,
				is_final tinyint(1) NOT NULL default 0,
				requires_approval tinyint(1) NOT NULL default 0,
				requires_note tinyint(1) NOT NULL default 0,
				is_active tinyint(1) NOT NULL default 1,
				metadata longtext DEFAULT NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY flow_id (flow_id),
				KEY step_order (step_order),
				KEY is_initial (is_initial),
				KEY is_active (is_active),
				UNIQUE KEY flow_step_key (flow_id,step_key)
			) {$charset_collate};",
			"CREATE TABLE {$processes_table} (
				id bigint(20) unsigned NOT NULL auto_increment,
				business_id bigint(20) unsigned NOT NULL default 1,
				vehicle_id bigint(20) unsigned NOT NULL,
				client_id bigint(20) unsigned DEFAULT 0,
				flow_id bigint(20) unsigned DEFAULT 0,
				process_type varchar(50) NOT NULL,
				title varchar(190) NOT NULL,
				description text DEFAULT NULL,
				internal_notes longtext DEFAULT NULL,
				current_step_id bigint(20) unsigned DEFAULT NULL,
				status varchar(50) NOT NULL default 'draft',
				priority varchar(50) NOT NULL default 'normal',
				opened_at datetime DEFAULT NULL,
				due_date datetime DEFAULT NULL,
				completed_at datetime DEFAULT NULL,
				closed_at datetime DEFAULT NULL,
				created_by bigint(20) unsigned DEFAULT NULL,
				assigned_to bigint(20) unsigned DEFAULT NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY business_id (business_id),
				KEY vehicle_id (vehicle_id),
				KEY client_id (client_id),
				KEY flow_id (flow_id),
				KEY current_step_id (current_step_id),
				KEY status (status),
				KEY process_type (process_type),
				KEY opened_at (opened_at),
				KEY due_date (due_date)
			) {$charset_collate};",
			"CREATE TABLE {$appointments_table} (
				id bigint(20) unsigned NOT NULL auto_increment,
				business_id bigint(20) unsigned NOT NULL default 1,
				client_id bigint(20) unsigned NOT NULL,
				vehicle_id bigint(20) unsigned NOT NULL,
				process_id bigint(20) unsigned DEFAULT NULL,
				assigned_to bigint(20) unsigned NOT NULL,
				appointment_status varchar(50) NOT NULL default 'scheduled',
				appointment_date date NOT NULL,
				start_at datetime NOT NULL,
				notes text DEFAULT NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY business_id (business_id),
				KEY client_id (client_id),
				KEY vehicle_id (vehicle_id),
				KEY process_id (process_id),
				KEY assigned_to (assigned_to),
				KEY appointment_status (appointment_status),
				KEY appointment_date (appointment_date),
				KEY start_at (start_at)
			) {$charset_collate};",
			"CREATE TABLE {$appointment_sync_table} (
				id bigint(20) unsigned NOT NULL auto_increment,
				business_id bigint(20) unsigned NOT NULL default 1,
				appointment_id bigint(20) unsigned NOT NULL,
				provider varchar(50) NOT NULL default 'google_calendar',
				external_calendar_id varchar(191) DEFAULT NULL,
				external_event_id varchar(191) DEFAULT NULL,
				sync_status varchar(50) NOT NULL default 'pending',
				last_synced_at datetime DEFAULT NULL,
				last_sync_hash varchar(191) DEFAULT NULL,
				last_error text DEFAULT NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY business_id (business_id),
				KEY appointment_id (appointment_id),
				KEY provider (provider),
				KEY sync_status (sync_status),
				UNIQUE KEY provider_appointment (provider,appointment_id),
				UNIQUE KEY provider_external_event (provider,external_event_id)
			) {$charset_collate};",
			"CREATE TABLE {$step_logs_table} (
				id bigint(20) unsigned NOT NULL auto_increment,
				business_id bigint(20) unsigned NOT NULL default 1,
				process_id bigint(20) unsigned NOT NULL,
				flow_step_id bigint(20) unsigned DEFAULT NULL,
				action_type varchar(50) NOT NULL,
				message text DEFAULT NULL,
				internal_note text DEFAULT NULL,
				customer_visible tinyint(1) NOT NULL default 0,
				created_by bigint(20) unsigned DEFAULT NULL,
				created_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY business_id (business_id),
				KEY process_id (process_id),
				KEY flow_step_id (flow_step_id),
				KEY action_type (action_type),
				KEY customer_visible (customer_visible)
			) {$charset_collate};",
			"CREATE TABLE {$parts_table} (
				id bigint(20) unsigned NOT NULL auto_increment,
				process_id bigint(20) unsigned NOT NULL,
				part_name varchar(190) NOT NULL,
				part_code varchar(100) DEFAULT NULL,
				quantity decimal(10,2) NOT NULL default 1.00,
				unit_price decimal(12,2) DEFAULT NULL,
				total_price decimal(12,2) DEFAULT NULL,
				status varchar(50) NOT NULL default 'pending',
				note text DEFAULT NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY process_id (process_id),
				KEY status (status),
				KEY part_code (part_code)
			) {$charset_collate};",
			"CREATE TABLE {$process_meta_table} (
				id bigint(20) unsigned NOT NULL auto_increment,
				process_id bigint(20) unsigned NOT NULL,
				meta_key varchar(191) NOT NULL,
				meta_value longtext DEFAULT NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY process_id (process_id),
				KEY meta_key (meta_key),
				KEY process_meta_key (process_id,meta_key)
			) {$charset_collate};",
			"CREATE TABLE {$maintenance_table} (
				id bigint(20) unsigned NOT NULL auto_increment,
				process_id bigint(20) unsigned NOT NULL,
				diagnosis longtext DEFAULT NULL,
				client_approved tinyint(1) NOT NULL default 0,
				approved_at datetime DEFAULT NULL,
				mechanic_id bigint(20) unsigned DEFAULT NULL,
				estimated_hours decimal(10,2) DEFAULT NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY process_id (process_id),
				KEY mechanic_id (mechanic_id),
				KEY client_approved (client_approved)
			) {$charset_collate};",
			"CREATE TABLE {$maintenance_parts} (
				id bigint(20) unsigned NOT NULL auto_increment,
				maintenance_id bigint(20) unsigned NOT NULL,
				part_name varchar(190) NOT NULL,
				quantity decimal(10,2) NOT NULL default 1.00,
				unit_price decimal(12,2) NOT NULL default 0.00,
				total_price decimal(12,2) NOT NULL default 0.00,
				notes text DEFAULT NULL,
				created_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY maintenance_id (maintenance_id)
			) {$charset_collate};",
			"CREATE TABLE {$maintenance_labor} (
				id bigint(20) unsigned NOT NULL auto_increment,
				maintenance_id bigint(20) unsigned NOT NULL,
				description varchar(190) NOT NULL,
				hours decimal(10,2) NOT NULL default 0.00,
				hour_rate decimal(12,2) NOT NULL default 0.00,
				total_price decimal(12,2) NOT NULL default 0.00,
				created_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY maintenance_id (maintenance_id)
			) {$charset_collate};",
			"CREATE TABLE {$pre_delivery_table} (
				id bigint(20) unsigned NOT NULL auto_increment,
				process_id bigint(20) unsigned NOT NULL,
				insurance_required tinyint(1) NOT NULL default 0,
				insurance_completed tinyint(1) NOT NULL default 0,
				insurance_completed_at datetime DEFAULT NULL,
				plate_required tinyint(1) NOT NULL default 0,
				plate_completed tinyint(1) NOT NULL default 0,
				plate_completed_at datetime DEFAULT NULL,
				final_review_required tinyint(1) NOT NULL default 0,
				final_review_completed tinyint(1) NOT NULL default 0,
				final_review_completed_at datetime DEFAULT NULL,
				delivery_ready tinyint(1) NOT NULL default 0,
				delivery_ready_at datetime DEFAULT NULL,
				assigned_user_id bigint(20) unsigned DEFAULT NULL,
				notes text DEFAULT NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY process_id (process_id),
				KEY assigned_user_id (assigned_user_id),
				KEY delivery_ready (delivery_ready)
			) {$charset_collate};",
			"CREATE TABLE {$paperwork_table} (
				id bigint(20) unsigned NOT NULL auto_increment,
				process_id bigint(20) unsigned NOT NULL,
				paperwork_type varchar(100) DEFAULT NULL,
				target_date date DEFAULT NULL,
				completed_date date DEFAULT NULL,
				assigned_user_id bigint(20) unsigned DEFAULT NULL,
				status varchar(50) NOT NULL default 'pending',
				notes text DEFAULT NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY process_id (process_id),
				KEY assigned_user_id (assigned_user_id),
				KEY status (status),
				KEY target_date (target_date)
			) {$charset_collate};",
			"CREATE TABLE {$paperwork_items_table} (
				id bigint(20) unsigned NOT NULL auto_increment,
				paperwork_id bigint(20) unsigned NOT NULL,
				item_key varchar(100) NOT NULL,
				item_label varchar(150) NOT NULL,
				is_required tinyint(1) NOT NULL default 0,
				is_completed tinyint(1) NOT NULL default 0,
				completed_at datetime DEFAULT NULL,
				notes text DEFAULT NULL,
				sort_order int(10) unsigned NOT NULL default 0,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY paperwork_id (paperwork_id),
				KEY sort_order (sort_order),
				KEY is_completed (is_completed)
			) {$charset_collate};",
			"CREATE TABLE {$quotes_table} (
				id bigint(20) unsigned NOT NULL auto_increment,
				business_id bigint(20) unsigned NOT NULL default 1,
				process_id bigint(20) unsigned NOT NULL,
				client_id bigint(20) unsigned DEFAULT NULL,
				quote_number varchar(100) NOT NULL,
				status varchar(50) NOT NULL default 'draft',
				currency varchar(10) NOT NULL default 'USD',
				subtotal decimal(12,2) NOT NULL default 0.00,
				tax_total decimal(12,2) NOT NULL default 0.00,
				discount_total decimal(12,2) NOT NULL default 0.00,
				grand_total decimal(12,2) NOT NULL default 0.00,
				notes longtext DEFAULT NULL,
				approved_by_client tinyint(1) NOT NULL default 0,
				approved_at datetime DEFAULT NULL,
				rejected_at datetime DEFAULT NULL,
				rejection_reason text DEFAULT NULL,
				created_by bigint(20) unsigned DEFAULT NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY business_id (business_id),
				UNIQUE KEY quote_number (quote_number),
				KEY process_id (process_id),
				KEY client_id (client_id),
				KEY status (status),
				KEY approved_by_client (approved_by_client)
			) {$charset_collate};",
			"CREATE TABLE {$quote_items_table} (
				id bigint(20) unsigned NOT NULL auto_increment,
				business_id bigint(20) unsigned NOT NULL default 1,
				quote_id bigint(20) unsigned NOT NULL,
				item_type varchar(20) NOT NULL,
				reference_id bigint(20) unsigned DEFAULT NULL,
				label varchar(190) NOT NULL,
				description text DEFAULT NULL,
				quantity decimal(10,2) NOT NULL default 1.00,
				unit_price decimal(12,2) NOT NULL default 0.00,
				line_total decimal(12,2) NOT NULL default 0.00,
				sort_order int(10) unsigned NOT NULL default 0,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY business_id (business_id),
				KEY quote_id (quote_id),
				KEY item_type (item_type),
				KEY sort_order (sort_order)
			) {$charset_collate};",
			"CREATE TABLE {$invoices_table} (
				id bigint(20) unsigned NOT NULL auto_increment,
				business_id bigint(20) unsigned NOT NULL default 1,
				process_id bigint(20) unsigned DEFAULT NULL,
				quote_id bigint(20) unsigned DEFAULT NULL,
				client_id bigint(20) unsigned DEFAULT NULL,
				invoice_number varchar(100) NOT NULL,
				status varchar(50) NOT NULL default 'draft',
				currency varchar(10) NOT NULL default 'USD',
				subtotal decimal(12,2) NOT NULL default 0.00,
				tax_total decimal(12,2) NOT NULL default 0.00,
				discount_total decimal(12,2) NOT NULL default 0.00,
				grand_total decimal(12,2) NOT NULL default 0.00,
				amount_paid decimal(12,2) NOT NULL default 0.00,
				balance_due decimal(12,2) NOT NULL default 0.00,
				issued_at datetime DEFAULT NULL,
				due_date date DEFAULT NULL,
				paid_at datetime DEFAULT NULL,
				notes longtext DEFAULT NULL,
				created_by bigint(20) unsigned DEFAULT NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY business_id (business_id),
				UNIQUE KEY invoice_number (invoice_number),
				KEY process_id (process_id),
				KEY quote_id (quote_id),
				KEY client_id (client_id),
				KEY status (status),
				KEY due_date (due_date)
			) {$charset_collate};",
			"CREATE TABLE {$invoice_items_table} (
				id bigint(20) unsigned NOT NULL auto_increment,
				business_id bigint(20) unsigned NOT NULL default 1,
				invoice_id bigint(20) unsigned NOT NULL,
				item_type varchar(20) NOT NULL,
				reference_id bigint(20) unsigned DEFAULT NULL,
				label varchar(190) NOT NULL,
				description text DEFAULT NULL,
				quantity decimal(10,2) NOT NULL default 1.00,
				unit_price decimal(12,2) NOT NULL default 0.00,
				line_total decimal(12,2) NOT NULL default 0.00,
				sort_order int(10) unsigned NOT NULL default 0,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY business_id (business_id),
				KEY invoice_id (invoice_id),
				KEY item_type (item_type),
				KEY sort_order (sort_order),
				KEY invoice_sort_order (invoice_id,sort_order)
			) {$charset_collate};",
			"CREATE TABLE {$payments_table} (
				id bigint(20) unsigned NOT NULL auto_increment,
				business_id bigint(20) unsigned NOT NULL default 1,
				invoice_id bigint(20) unsigned NOT NULL,
				payment_date datetime NOT NULL,
				amount decimal(12,2) NOT NULL default 0.00,
				payment_method varchar(50) NOT NULL,
				reference varchar(100) DEFAULT NULL,
				notes text DEFAULT NULL,
				received_by bigint(20) unsigned DEFAULT NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY business_id (business_id),
				KEY invoice_id (invoice_id),
				KEY payment_date (payment_date),
				KEY payment_method (payment_method),
				KEY invoice_payment_date (invoice_id,payment_date)
			) {$charset_collate};",
			"CREATE TABLE {$attachments_table} (
				id bigint(20) unsigned NOT NULL auto_increment,
				business_id bigint(20) unsigned NOT NULL default 1,
				object_type varchar(50) NOT NULL default 'process',
				object_id bigint(20) unsigned NOT NULL default 0,
				process_id bigint(20) unsigned DEFAULT NULL,
				client_id bigint(20) unsigned DEFAULT NULL,
				vehicle_id bigint(20) unsigned DEFAULT NULL,
				attachment_type varchar(50) NOT NULL default 'document',
				title varchar(190) NOT NULL,
				description text DEFAULT NULL,
				file_url text NOT NULL,
				file_path text DEFAULT NULL,
				mime_type varchar(100) NOT NULL,
				file_size bigint(20) unsigned NOT NULL default 0,
				is_internal tinyint(1) NOT NULL default 1,
				is_client_visible tinyint(1) NOT NULL default 0,
				uploaded_by bigint(20) unsigned DEFAULT NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY business_id (business_id),
				KEY object_type (object_type),
				KEY object_id (object_id),
				KEY process_id (process_id),
				KEY client_id (client_id),
				KEY vehicle_id (vehicle_id),
				KEY attachment_type (attachment_type),
				KEY is_internal (is_internal),
				KEY is_client_visible (is_client_visible)
			) {$charset_collate};",
            "CREATE TABLE {$comments_table} (
                id bigint(20) unsigned NOT NULL auto_increment,
                business_id bigint(20) unsigned NOT NULL default 1,
                object_type varchar(50) NOT NULL,
                object_id bigint(20) unsigned NOT NULL default 0,
                process_id bigint(20) unsigned DEFAULT NULL,
                client_id bigint(20) unsigned DEFAULT NULL,
                vehicle_id bigint(20) unsigned DEFAULT NULL,
                parent_id bigint(20) unsigned DEFAULT NULL,
                author_user_id bigint(20) unsigned DEFAULT NULL,
                author_client_id bigint(20) unsigned DEFAULT NULL,
                comment_type varchar(50) NOT NULL default 'internal_note',
                content longtext NOT NULL,
                is_internal tinyint(1) NOT NULL default 1,
                is_client_visible tinyint(1) NOT NULL default 0,
                status varchar(30) NOT NULL default 'published',
                created_at datetime NOT NULL,
                updated_at datetime NOT NULL,
                PRIMARY KEY  (id),
                KEY business_id (business_id),
                KEY object_type (object_type),
                KEY object_id (object_id),
                KEY process_id (process_id),
                KEY client_id (client_id),
                KEY vehicle_id (vehicle_id),
                KEY parent_id (parent_id),
                KEY author_user_id (author_user_id),
                KEY author_client_id (author_client_id),
                KEY comment_type (comment_type),
                KEY is_internal (is_internal),
                KEY is_client_visible (is_client_visible),
                KEY status (status)
            ) {$charset_collate};",
            "CREATE TABLE {$notifications_table} (
                id bigint(20) unsigned NOT NULL auto_increment,
                business_id bigint(20) unsigned NOT NULL default 1,
                recipient_type varchar(20) NOT NULL,
                recipient_id bigint(20) unsigned NOT NULL,
                object_type varchar(50) DEFAULT NULL,
                object_id bigint(20) unsigned DEFAULT NULL,
                process_id bigint(20) unsigned DEFAULT NULL,
                notification_type varchar(50) NOT NULL,
                title varchar(190) NOT NULL,
                message text DEFAULT NULL,
                data_json longtext DEFAULT NULL,
                is_read tinyint(1) NOT NULL default 0,
                read_at datetime DEFAULT NULL,
                created_at datetime NOT NULL,
                updated_at datetime NOT NULL,
                is_system tinyint(1) NOT NULL default 1,
                PRIMARY KEY  (id),
                KEY business_id (business_id),
                KEY recipient_type (recipient_type),
                KEY recipient_id (recipient_id),
                KEY object_type (object_type),
                KEY object_id (object_id),
                KEY process_id (process_id),
                KEY notification_type (notification_type),
                KEY is_read (is_read),
                KEY is_system (is_system)
            ) {$charset_collate};",
			"CREATE TABLE {$webhooks_table} (
				id bigint(20) unsigned NOT NULL auto_increment,
				business_id bigint(20) unsigned NOT NULL default 1,
				name varchar(190) NOT NULL,
				endpoint_url varchar(255) NOT NULL,
				secret_encrypted longtext NOT NULL,
				secret_hash varchar(191) NOT NULL,
				events_json longtext NOT NULL,
				status varchar(20) NOT NULL default 'inactive',
				last_used_at datetime DEFAULT NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY (id),
				KEY business_id (business_id),
				KEY status (status)
			) {$charset_collate};",
			"CREATE TABLE {$webhook_deliveries_table} (
				id bigint(20) unsigned NOT NULL auto_increment,
				business_id bigint(20) unsigned NOT NULL default 1,
				webhook_id bigint(20) unsigned NOT NULL,
				event_key varchar(120) NOT NULL,
				event_id varchar(191) NOT NULL,
				payload_json longtext NOT NULL,
				status varchar(20) NOT NULL default 'pending',
				attempts smallint(5) unsigned NOT NULL default 0,
				next_retry_at datetime DEFAULT NULL,
				last_attempt_at datetime DEFAULT NULL,
				last_http_code smallint(5) unsigned NOT NULL default 0,
				last_error text DEFAULT NULL,
				delivered_at datetime DEFAULT NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY (id),
				UNIQUE KEY webhook_event (webhook_id,event_id),
				KEY business_id (business_id),
				KEY status_next_retry (status,next_retry_at),
				KEY event_key (event_key)
			) {$charset_collate};",
			"CREATE TABLE {$saas_queue_jobs_table} (
				id bigint(20) unsigned NOT NULL auto_increment,
				job_id varchar(64) NOT NULL,
				job_type varchar(64) NOT NULL,
				business_id bigint(20) unsigned NOT NULL,
				tenant_id varchar(64) DEFAULT NULL,
				payload_json longtext DEFAULT NULL,
				status varchar(32) NOT NULL default 'pending',
				attempts int(10) unsigned NOT NULL default 0,
				max_attempts int(10) unsigned NOT NULL default 3,
				scheduled_at datetime DEFAULT NULL,
				available_at datetime DEFAULT NULL,
				locked_at datetime DEFAULT NULL,
				lock_token varchar(128) DEFAULT NULL,
				last_error text DEFAULT NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY job_id (job_id),
				KEY job_type (job_type),
				KEY business_id (business_id),
				KEY status (status),
				KEY available_at (available_at),
				KEY scheduled_at (scheduled_at)
			) {$charset_collate};",
		);
	}
}


